apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: devops
type: Opaque
data:
  gitlab_root_username: c2VydmVybGVzLWNkQDE2My5jb20=
  gitlab_root_password: MWYyZDFlMmU2N2Rm
  gitlab_host: Z2l0bGFiLmMxNjE5NDY2MGYxNDU0ODk4YTA4MTA0MDgxNzEzMDJhYy5jbi1zaGFuZ2hhaS5hbGljb250YWluZXIuY29t

---
# ConfigMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
data:
  gitlab_host: gitlab.c16194660f1454898a0810408171302ac.cn-shanghai.alicontainer.com

---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/service-weight: ''
  name: gitlab
  namespace: devops
spec:
  ingressClassName: nginx
  rules:
    - host: gitlab.c16194660f1454898a0810408171302ac.cn-shanghai.alicontainer.com
      http:
        paths:
          - backend:
              service:
                name: gitlab
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific